import { createContext, useContext, useState, useEffect } from 'react';

const LangContext = createContext();

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used inside <LangProvider>');
  return ctx;
};

export const LANGUAGES = [
  { code: 'en', label: 'EN', full: 'English' },
  { code: 'hi', label: 'हि',  full: 'हिन्दी' },
  { code: 'te', label: 'తె',  full: 'తెలుగు' },
];

const STRINGS = {
  en: {
    dashboard: 'Dashboard', findWork: 'Find Work', myWork: 'My Work',
    wallet: 'Wallet', history: 'History', messages: 'Messages',
    portfolio: 'Portfolio', notifications: 'Notifications',
    myProfile: 'My Profile', verification: 'Verification', help: 'Help',
    logout: 'Logout', postJob: 'Post a Job', myJobPosts: 'My Job Posts',
    findWorkers: 'Find Workers', home: 'Home', profile: 'Profile',
    save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete',
    select: 'Select', search: 'Search', apply: 'Apply', loading: 'Loading...',
    back: 'Back', submit: 'Submit', close: 'Close', confirm: 'Confirm',
    yourSkill: 'Your skill', city: 'City', area: 'Area',
    experience: 'Experience (years)', dailyWage: 'Daily wage (₹)',
    available: 'I am available for work', aboutYou: 'About yourself',
    languages: 'Languages', fullName: 'Full name', phoneNumber: 'Phone number',
    age: 'Age', gender: 'Gender', saveProfile: 'Save Profile',
    editProfile: 'Edit Profile', yourRating: 'Your Rating',
    browseJobs: 'Browse jobs', noJobs: 'No jobs available right now',
    jobsAvailable: 'jobs available', perDay: 'per day',
    workersNeeded: 'workers needed', applied: 'Applied', accepted: 'Accepted',
    urgent: 'URGENT', acceptNow: 'Accept now', jobPoster: 'Job poster',
    notStarted: 'Waiting to start', inProgress: 'Work in progress',
    completed: 'Work completed', markStarted: 'Mark Work as Started',
    markCompleted: 'Mark Work as Completed', trackWorker: 'Track worker live',
    rateWorker: 'Rate Worker', rateContractor: 'Rate this poster',
    online: "You're Online", offline: "You're Offline",
    goOnline: 'Go Online', goOffline: 'Go Offline',
    readyForWork: 'Ready to receive job requests',
    notReceiving: 'You will not receive new job alerts',
    totalEarned: 'Total earned', totalPaid: 'Total paid',
    monthlyEarnings: 'Monthly earnings', averagePerJob: 'Average per job',
    jobsDone: 'Jobs done', noRecords: 'No records yet',
    goodMorning: 'Good morning', goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening', quickActions: 'Quick actions',
    subscription: 'Subscription',

    // ── NEW: Dashboard ──
    jobsPosted: 'Jobs posted', rating: 'Rating', worker: 'Worker', user: 'User',
    readyToReceive: (skill) => `Ready to receive ${skill} job requests`,
    findWorkTitle: 'Browse Jobs',      findWorkSub: 'Kaam dhundo',
    myWorkTitle: 'My Work',            myWorkSub: 'Mera kaam',
    portfolioTitle: 'Portfolio',       portfolioSub: 'Kaam ki photos',
    verificationTitle: 'Verification', verificationSub: 'ID verify karo',
    postJobTitle: 'Post a Job',        postJobSub: 'Kaam post karo',
    myJobPostsTitle: 'My Job Posts',   myJobPostsSub: 'Mere jobs',
    findWorkersTitle: 'Find Workers',  findWorkersSub: 'Worker dhundo',

    // ── NEW: Common actions/labels used across many pages ──
    filters: 'Filters', clear: 'Clear', clearFilters: 'Clear filters',
    allSkills: 'All skills', allCities: 'All cities', allTypes: 'All types',
    regular: 'Regular', partTime: 'Part-time', urgentOnly: 'Urgent only',
    searchJobs: 'Search jobs', voiceSearch: 'Voice search',
    noJobsFound: 'No jobs available right now', tryRemovingFilters: 'Try removing some filters, or check back soon',
    willNotify: 'We will notify you when a new job matches your skill',
    jobFull: 'Job Full', call: 'Call', chat: 'Chat',
    postedBy: 'Posted by', kmAway: 'km away',
    showingWithin: (km) => `Showing jobs within ${km}km of you`,
    noJobsExpanded: (km) => `No jobs within 6km — showing up to ${km}km instead`,
    locationDenied: 'Location access denied — showing jobs by city/skill filter instead',

    // ── NEW: History ──
    historyTitle: 'History', historyTagline: 'Purane kaam — your completed jobs',
    completedJobs: 'Completed jobs', completedOn: 'Completed', worked: 'You worked for',
    rated: 'Rated', ratePoster: 'Rate poster', rateWorkerBtn: 'Rate worker',
    noHistory: 'No completed jobs yet', noHistoryWorker: 'Finish your first job and it will appear here',
    noHistoryUser: 'Once a worker completes a job, it will appear here',

    // ── NEW: Notifications ──
    notifTitle: 'Notifications', notifTagline: 'Suchnaye — stay updated',
    markAllRead: 'Mark all read', clear: 'Clear',
    noNotifs: 'No notifications yet', noNotifsSub: 'Job updates and messages will appear here',

    // ── NEW: Portfolio ──
    myPortfolio: 'My Portfolio', portfolioTagline: 'Kaam ki photos — show your best work',
    addWork: 'Add work', addPastWork: 'Add past work', title: 'Title',
    skillUsed: 'Skill used', photosMax: 'Photos (max 5)', description: 'Description',
    chooseFiles: 'Choose Files', noFileChosen: 'No file chosen',
    describeWork: 'Describe the work you did...', noPortfolio: 'No portfolio items yet',
    noPortfolioSub: 'Add photos of your past work to attract more clients',

    // ── NEW: Help ──
    helpTitle: 'Help & Support', helpTagline: 'Sahayata — we are here to help',
    chatWithUs: 'Chat with Us', whatsappSupport: 'WhatsApp Support', fastestResponse: 'Fastest response',
    callSupport: 'Call Support', emailUs: 'Email us', faqTitle: 'Frequently Asked Questions',
    needMoreHelp: 'Need more help?', messageOnWhatsapp: 'Message us on WhatsApp',
    termsConditions: 'Terms & Conditions', privacyPolicy: 'Privacy Policy',

    // ── NEW: Wallet ──
    walletTitle: 'Wallet', walletTaglineWorker: 'Meri kamai — your earning records',
    walletTaglineUser: 'Payment records for completed jobs',
    filterBy: 'Filter by', monthlyEarnings2: 'Monthly earnings', monthlyPayments: 'Monthly payments',
    avgEarning: 'Average earning', avgPayment: 'Average payment', jobsDone2: 'Jobs done',
    completedThisMonth: 'Completed this month', lifetimeEarnings: 'Lifetime earnings',
    lifetimePayments: 'Lifetime payments', totalRecords: 'total records',
    earningsHistory: 'Earnings history', paymentHistory: 'Payment history',
    noRecordsIn: (m, y) => `No records in ${m} ${y}`, tryDifferentMonth: 'Try selecting a different month',
    completeFirstJobWorker: 'Complete your first job and your earning will show here',
    completeFirstJobUser: 'Complete a job with a worker and the record will show here',
    from: 'From', to2: 'To', walletInfoWorker: 'Amounts appear here automatically when your work is marked completed. Payment itself happens directly between you and the job poster (cash or UPI) — Instant Worker takes no commission.',
    walletInfoUser: "Records appear here automatically when you mark a worker's job as completed. Payment itself happens directly between you and the worker (cash or UPI).",

    // ── NEW: Verification ──
    idVerificationTitle: 'ID Verification', notVerifiedYet: 'Not verified yet',
    underReview: 'Under review', verifiedStatus: 'Verified ✓', verificationRejected: 'Verification rejected',
    verifyMyIdentity: 'Verify my identity', resubmitId: 'Resubmit ID',
    idType: 'ID Type', selectIdType: 'Select ID type', idNumberOptional: 'ID Number (optional, kept private)',
    photoOfId: 'Photo of your ID', tapToUpload: 'Tap to take photo or upload',
    makeSureVisible: 'Make sure all details are clearly visible',
    selfieOptional: 'Selfie holding your ID (optional, speeds up approval)', tapAddSelfie: 'Tap to add selfie',
    submitForReview: 'Submit for review', submitting: 'Submitting...',
    privacyNoteVerify: 'Your ID document is only visible to our verification team. We never show your full ID number publicly — only the last 4 digits if you choose to share them.',
    getVerifiedBadge: 'Get a verified badge on your profile. Contractors trust verified workers more.',
    reviewWithin: 'We review within 24-48 hours.',
    identityVerified: 'Your identity is verified. A verified badge now shows on your profile.',
    canResubmit: 'You can submit again with a clearer photo.',

    // ── NEW: Conversations ──
    messagesTitle: 'Messages', messagesTagline: 'Baatcheet — your chats',
    refresh: 'Refresh', noConversations: 'No conversations yet',
    chatOpensAfter: 'Chat opens after a job application is accepted',
    viewMyJobs: 'View my jobs', justNow: 'Just now', newBadge: 'NEW',
    chatUnlockedSayHello: 'Chat unlocked — say hello!',
    acceptedFor: (title) => `Accepted for: ${title}`,

    // ── NEW: Notification message builders (title + body constructed
    // client-side from raw data, so they render in the current language
    // instead of whatever language they were created in) ──
    notifJobAppliedTitle: 'New applicant!',
    notifJobAppliedBody: (name, job) => `${name} applied to your job: ${job}`,
    notifAcceptedTitle: 'You got the job! 🎉',
    notifAcceptedBody: (job) => `Your application for "${job}" was accepted. You can now chat with the poster.`,
    notifRejectedTitle: 'Application not selected',
    notifRejectedBody: (job) => `Your application for "${job}" was not selected this time.`,
    notifWorkStartedTitle: 'Work has started! 🔨',
    notifWorkStartedBody: (name, job) => `${name} marked "${job}" as started. Time to begin work!`,
    notifWorkCompletedTitle: 'Work completed! ✅',
    notifWorkCompletedBody: (name, job, amount) => `${name} marked "${job}" as completed. ₹${amount} added to your wallet records. Don't forget to rate them!`,
    notifUrgentJobTitle: '🔴 Urgent work nearby!',
    notifUrgentJobBody: (job, skill, city, wage) => `${job} — ${skill} needed NOW in ${city}. ₹${wage}/day. Tap to respond fast!`,
    notifUrgentFilledTitle: 'Urgent job — worker confirmed! ⚡',
    notifUrgentFilledBody: (name, job) => `${name} accepted your urgent job "${job}" and is on the way. Chat is open now.`,

    // ── NEW: Browse Jobs / Job Card ──
    findWorkTagline: 'Kaam dhundo', searching: 'searching...',
    jobsAvailable2: (n) => `${n} job${n !== 1 ? 's' : ''} available`,
    skill: 'Skill', jobType: 'Job type', searchJobsBtn: 'Search jobs',
    loadingJobs: 'Loading jobs...', minutesAgo: (n) => `${n}m ago`, hoursAgo: (n) => `${n}h ago`, daysAgo: (n) => `${n}d ago`,
    by: 'By', needed: 'needed', minAgo: 'm ago',

    // ── NEW: Login page ──
    loginTagline1: 'Skilled work,', loginTagline2: 'just a tap away.',
    loginValueCopy: 'Find work or hire verified workers in minutes — with zero commission, live tracking, and support in your language.',
    loginBullet1: '100% free for workers — no commission ever',
    loginBullet2: 'ID-verified profiles with real ratings',
    loginBullet3: 'Live tracking, like following a cab',
    footerCopyright: '© 2026 Instant Worker · Andhra Pradesh & Telangana',
    welcomeBackTitle: 'Welcome back', loginSubtitle: 'Log in to continue to your account',
    sessionExpiredMsg: 'Your session expired. Please log in again.',
    mobileNumberField: 'Mobile number', tenDigitNumber: '10-digit number',
    passwordField: 'Password', yourPasswordPh: 'Your password',
    loggingInBtn: 'Logging in...', logInBtn: 'Log in', newHere: 'New here?',
    createFreeAccount: 'Create a free account',
    byLoggingIn: 'By logging in you agree to our', andWord: 'and',
    termsLink: 'Terms', privacyLink: 'Privacy Policy', agreeSuffix: '',
    wrongCredentials: 'Wrong phone number or password',

    // ── NEW: Register page ──
    createAccountTitle: 'Create your account', howWillYouUse: 'How will you use Instant Worker?',
    iWantToWork: 'I want to work', findJobsNearYou: 'Find jobs near you',
    iNeedWorkers: 'I need workers', postJobsAndHire: 'Post jobs and hire',
    yourDetailsTitle: 'Your details', weWillVerifyNext: "We'll verify your number with an OTP next",
    fullNameLabel: 'Full name', yourNamePh: 'Your name',
    mobileNumberReg: 'Mobile number', tenDigitNumberReg: '10-digit number',
    passwordLabel: 'Password', atLeast6Chars: 'At least 6 characters',
    yourMainSkill: 'Your main skill', selectSkillPh: 'Select skill',
    continueToVerification: 'Continue to verification', creatingAccount: 'Creating your account...',
    enterOtpInPopup: 'Enter the OTP sent to your phone in the popup...',
    alreadyHaveAccount: 'Already have an account?', logInLink: 'Log in',
    backBtn: 'Back', registrationUnavailable: 'Registration is temporarily unavailable — missing OTP configuration. Please contact support.',
    validPhoneErr: 'Enter a valid 10-digit mobile number',
    verifyFailedErr: 'Phone verification failed or was cancelled. Please try again.',
    couldNotComplete: 'Could not complete registration',

    // ── NEW: Landing page — nav & header ──
    navServices: 'Services', navHow: 'How it works', navAbout: 'About', navFaq: 'FAQ', navContact: 'Contact',
    loginNav: 'Login', getStarted: 'Get Started',

    // ── Hero ──
    heroTagline: "India's instant work platform", heroTaglineCity: (city) => `India's instant work platform · ${city}`,
    heroH1a: 'Skilled workers.', heroH1b: 'On demand.', heroH1c: 'In minutes.',
    heroSubP1: 'Painters, carpenters, electricians, plumbers, drivers and daily-wage labour — hire verified workers or find work near you.',
    heroSubP2: 'No middlemen. Zero commission.',
    heroBtnWork: 'I want work', heroBtnHire: 'I need workers',
    heroStatCommission: 'Commission', heroStatRegister: 'To register', heroStatLanguages: 'Languages',
    floatWorkerConfirmed: 'Worker confirmed', floatArriving: 'Arriving in 18 minutes',
    floatRating: '4.8 rating', floatVerifiedElectrician: 'ID-verified electrician',

    // ── Services ──
    servicesTag: 'What we provide', servicesH2: 'One platform. Two sides. Everything you need.',
    servicesSub: "Whether you're looking for daily work or need trusted hands for a job — Instant Worker connects both sides directly.",
    forWorkersBadge: 'FOR WORKERS', forWorkersTitle: 'Find work near you — free forever',
    workerBullet1: 'Jobs matched to your skill and city, delivered to your phone',
    workerBullet2: 'Set your own daily wage — keep 100% of it',
    workerBullet3: 'Go Online / Offline anytime, you control when you work',
    workerBullet4: 'Build a photo portfolio and earn ratings that get you hired more',
    startFindingWork: 'Start finding work',
    forPostersBadge: 'FOR JOB POSTERS', forPostersTitle: 'Hire verified workers in minutes',
    posterBullet1: 'Post a job and receive applications from nearby skilled workers',
    posterBullet2: 'Urgent hiring — first available worker auto-confirms in minutes',
    posterBullet3: 'Track your worker arriving live on the map, like a cab',
    posterBullet4: 'Check ID-verified badges, ratings, and past work photos before hiring',
    postFirstJob: 'Post your first job',

    // ── How it works ──
    howTag: 'How it works', howH2: "Three steps. That's it.",
    step1Title: 'Register free', step1Desc: 'Name, phone number, OTP. Choose Worker or Job Poster. Under 2 minutes, no documents required.',
    step2Title: 'Match instantly', step2Desc: 'Workers browse jobs near them. Posters get applications — or use Urgent mode for instant auto-confirmation.',
    step3Title: 'Work & get paid', step3Desc: 'Track arrival live, complete the work, pay directly in cash or UPI. We never touch your money.',

    // ── Features strip ──
    featUrgentTitle: 'Urgent hiring', featUrgentDesc: 'First to accept gets the job — confirmed in minutes.',
    featTrackTitle: 'Live tracking', featTrackDesc: 'Watch your worker arrive on the map in real time.',
    featIdTitle: 'ID verification', featIdDesc: 'Government-ID checked badges you can trust.',
    featChatTitle: 'Secure chat', featChatDesc: 'Chat and voice notes unlock after confirmation.',
    featZeroTitle: 'Zero commission', featZeroDesc: 'Direct payment. Workers keep every rupee.',
    featLangTitle: '3 languages', featLangDesc: 'Telugu, Hindi and English — with voice search.',

    // ── About ──
    aboutTag: 'About us', aboutH2: 'The days of standing at the labour adda are over.',
    aboutP1: 'Every morning, millions of skilled workers across India wait at street corners hoping someone will offer a day\'s work. Meanwhile, people who need those exact skills can\'t find anyone reliable.',
    aboutP2: (city) => `Instant Worker connects both sides directly — no agents, no cuts from anyone's wage. Starting in ${city}, built in Telugu, Hindi and English so everyone can use it, including those who can't read or type well.`,
    chipNoMiddlemen: 'No middlemen', chipZeroCommission: 'Zero commission', chipLocalFirst: 'Local first',
    builtForFairness: 'Built for fairness',

    // ── Testimonials ──
    testimonialsTag: 'Testimonials', testimonialsH2: 'What people are saying',
    testi1Name: 'Ravi K.', testi1Role: 'Painter · Hyderabad',
    testi1Quote: 'Earlier I stood at the labour adda from 6 AM hoping for work. Now jobs come to my phone. I got 2 painting jobs in my first 3 days.',
    testi2Name: 'Srinivas T.', testi2Role: 'Job poster · Vijayawada',
    testi2Quote: 'I needed 2 helpers urgently. Both were confirmed within 20 minutes and I could watch them arrive on the map.',
    testi3Name: 'Lakshmi D.', testi3Role: 'Job poster · Visakhapatnam',
    testi3Quote: "I checked the electrician's rating and photos of his past work before booking. The job was done well, no stress at all.",

    // ── FAQ ──
    lpFaqTag: 'FAQ', lpFaqH2: 'Frequently asked questions',
    faq1Q: 'Is Instant Worker really free for workers?',
    faq1A: 'Yes. Registration is free, finding jobs is free, and we take zero commission from your wages. Whatever wage you agree with the job poster is 100% yours.',
    faq2Q: 'How do workers get paid?',
    faq2A: 'Payment is made directly between the worker and the job poster — cash or UPI, whatever both agree. We recommend confirming the wage in chat before starting work, so there is a written record.',
    faq3Q: 'What if a poster refuses to pay after work?',
    faq3A: 'Report them immediately using the Report button on their profile. Our team reviews every report. Users with verified payment complaints are banned from the platform.',
    faq4Q: 'I cannot read or type well. Can I still use this?',
    faq4A: 'Yes — that is exactly who we built this for. You can search for jobs by speaking in Telugu, Hindi, or English, and job details can be read aloud. Registration needs only your name, phone number, and an OTP.',
    faq5Q: 'Why does the app need my location?',
    faq5A: "A worker's live location is shared ONLY while a job is active, so the job poster can see they are on the way — like tracking a cab. It stops automatically when work is done.",
    faq6Q: 'Are ID documents safe if I verify?',
    faq6A: 'Yes. ID verification is optional. Your document is seen only by our verification team, never shown publicly, and never shared with anyone. Only the "Verified" badge appears on your profile.',

    // ── Contact ──
    contactTag: 'Contact us', contactH2: "Questions? We're here to help.",
    contactSub: "Reach out on WhatsApp for the fastest response, or call during support hours. We reply to every message.",
    whatsappLabel: 'WhatsApp', whatsappSub: 'Fastest response',
    callUsLabel: 'Call us', emailLabel: 'Email',

    // ── Final CTA ──
    ctaH2: "Start today. It's free.",
    ctaSub: (city) => `Free registration · Zero commission · ${city}`,
    joinInstantWorker: 'Join Instant Worker',

    // ── Footer ──
    footerTagline: 'Connecting daily-wage workers with the people who need them — instantly, fairly, with zero commission.',
    footerExplore: 'Explore', footerLegalAccount: 'Legal & Account',
    footerRegisterFree: 'Register free', footerLogin: 'Login',
    footerTerms: 'Terms & Conditions', footerPrivacy: 'Privacy Policy',
    footerContact: 'Contact', footerWhatsappPrefix: 'WhatsApp:',
    footerRights: '© 2026 Instant Worker. All rights reserved.',
    footerMadeWith: 'Made with', footerMadeIn: 'in Andhra Pradesh',

    marqueePainters: 'Painters', marqueeCarpenters: 'Carpenters', marqueeElectricians: 'Electricians',
    marqueePlumbers: 'Plumbers', marqueeDrivers: 'Drivers', marqueeWelders: 'Welders',
    marqueeMechanics: 'Mechanics', marqueeFarmLabour: 'Farm Labour', marqueeHelpers: 'Helpers', marqueeMasons: 'Masons',
  },
  hi: {
    dashboard: 'डैशबोर्ड', findWork: 'काम ढूंढो', myWork: 'मेरा काम',
    wallet: 'वॉलेट', history: 'इतिहास', messages: 'संदेश',
    portfolio: 'पोर्टफोलियो', notifications: 'सूचनाएं',
    myProfile: 'मेरी प्रोफाइल', verification: 'सत्यापन', help: 'सहायता',
    logout: 'लॉग आउट', postJob: 'काम पोस्ट करें', myJobPosts: 'मेरे काम',
    findWorkers: 'मजदूर ढूंढो', home: 'होम', profile: 'प्रोफाइल',
    save: 'सेव करें', cancel: 'रद्द करें', edit: 'बदलें', delete: 'हटाएं',
    select: 'चुनें', search: 'खोजें', apply: 'आवेदन करें', loading: 'लोड हो रहा है...',
    back: 'वापस', submit: 'जमा करें', close: 'बंद करें', confirm: 'पुष्टि करें',
    yourSkill: 'आपका काम', city: 'शहर', area: 'इलाका',
    experience: 'अनुभव (साल)', dailyWage: 'दैनिक मजदूरी (₹)',
    available: 'मैं काम के लिए उपलब्ध हूं', aboutYou: 'अपने बारे में',
    languages: 'भाषाएं', fullName: 'पूरा नाम', phoneNumber: 'मोबाइल नंबर',
    age: 'उम्र', gender: 'लिंग', saveProfile: 'प्रोफाइल सेव करें',
    editProfile: 'प्रोफाइल बदलें', yourRating: 'आपकी रेटिंग',
    browseJobs: 'काम देखें', noJobs: 'अभी कोई काम उपलब्ध नहीं है',
    jobsAvailable: 'काम उपलब्ध', perDay: 'प्रति दिन',
    workersNeeded: 'मजदूर चाहिए', applied: 'आवेदन किया', accepted: 'स्वीकृत',
    urgent: 'तुरंत', acceptNow: 'अभी स्वीकारें', jobPoster: 'काम देने वाला',
    notStarted: 'शुरू होने का इंतज़ार', inProgress: 'काम चल रहा है',
    completed: 'काम पूरा हुआ', markStarted: 'काम शुरू करें',
    markCompleted: 'काम पूरा करें', trackWorker: 'मजदूर को ट्रैक करें',
    rateWorker: 'मजदूर को रेट करें', rateContractor: 'रेटिंग दें',
    online: 'आप ऑनलाइन हैं', offline: 'आप ऑफलाइन हैं',
    goOnline: 'ऑनलाइन जाएं', goOffline: 'ऑफलाइन जाएं',
    readyForWork: 'काम के लिए तैयार',
    notReceiving: 'आपको नए काम की सूचना नहीं मिलेगी',
    totalEarned: 'कुल कमाई', totalPaid: 'कुल भुगतान',
    monthlyEarnings: 'महीने की कमाई', averagePerJob: 'प्रति काम औसत',
    jobsDone: 'पूरे किए काम', noRecords: 'अभी कोई रिकॉर्ड नहीं',
    goodMorning: 'सुप्रभात', goodAfternoon: 'नमस्कार',
    goodEvening: 'शुभ संध्या', quickActions: 'तेज़ काम',
    subscription: 'सदस्यता',

    jobsPosted: 'पोस्ट किए गए काम', rating: 'रेटिंग', worker: 'मजदूर', user: 'उपयोगकर्ता',
    readyToReceive: (skill) => `${skill} काम के अनुरोध पाने के लिए तैयार`,
    findWorkTitle: 'काम ढूंढो',      findWorkSub: 'नौकरी खोजें',
    myWorkTitle: 'मेरा काम',         myWorkSub: 'मेरा काम देखें',
    portfolioTitle: 'पोर्टफोलियो',    portfolioSub: 'काम की फ़ोटो',
    verificationTitle: 'सत्यापन',    verificationSub: 'ID सत्यापित करें',
    postJobTitle: 'काम पोस्ट करें',   postJobSub: 'काम पोस्ट करो',
    myJobPostsTitle: 'मेरे काम',      myJobPostsSub: 'मेरी पोस्ट',
    findWorkersTitle: 'मजदूर ढूंढो',  findWorkersSub: 'वर्कर ढूंढो',

    filters: 'फ़िल्टर', clear: 'साफ़ करें', clearFilters: 'फ़िल्टर हटाएं',
    allSkills: 'सभी काम', allCities: 'सभी शहर', allTypes: 'सभी प्रकार',
    regular: 'सामान्य', partTime: 'पार्ट-टाइम', urgentOnly: 'सिर्फ़ तुरंत वाले',
    searchJobs: 'काम खोजें', voiceSearch: 'आवाज़ से खोजें',
    noJobsFound: 'अभी कोई काम उपलब्ध नहीं है', tryRemovingFilters: 'कुछ फ़िल्टर हटाएं, या बाद में देखें',
    willNotify: 'नया काम मिलते ही हम आपको बताएंगे',
    jobFull: 'जगह भर गई', call: 'कॉल करें', chat: 'चैट',
    postedBy: 'पोस्ट किया', kmAway: 'किमी दूर',
    showingWithin: (km) => `आपके ${km}किमी के अंदर के काम दिखाए जा रहे हैं`,
    noJobsExpanded: (km) => `6किमी में कोई काम नहीं — अब ${km}किमी तक दिखाया जा रहा है`,
    locationDenied: 'लोकेशन नहीं मिली — शहर/काम के अनुसार दिखाया जा रहा है',

    historyTitle: 'इतिहास', historyTagline: 'पुराने काम — आपके पूरे किए काम',
    completedJobs: 'पूरे किए काम', completedOn: 'पूरा हुआ', worked: 'आपने काम किया',
    rated: 'रेट किया गया', ratePoster: 'पोस्टर को रेट करें', rateWorkerBtn: 'मजदूर को रेट करें',
    noHistory: 'अभी कोई पूरा काम नहीं', noHistoryWorker: 'अपना पहला काम पूरा करें, यह यहाँ दिखेगा',
    noHistoryUser: 'जब मजदूर काम पूरा करेगा, यह यहाँ दिखेगा',

    notifTitle: 'सूचनाएं', notifTagline: 'सूचनाएं — अपडेट रहें',
    markAllRead: 'सभी पढ़ा हुआ मार्क करें', clear: 'साफ़ करें',
    noNotifs: 'अभी कोई सूचना नहीं', noNotifsSub: 'काम अपडेट और संदेश यहाँ दिखेंगे',

    myPortfolio: 'मेरा पोर्टफोलियो', portfolioTagline: 'काम की फ़ोटो — अपना बेहतरीन काम दिखाएं',
    addWork: 'काम जोड़ें', addPastWork: 'पुराना काम जोड़ें', title: 'शीर्षक',
    skillUsed: 'इस्तेमाल किया गया काम', photosMax: 'फ़ोटो (अधिकतम 5)', description: 'विवरण',
    chooseFiles: 'फ़ाइलें चुनें', noFileChosen: 'कोई फ़ाइल नहीं चुनी',
    describeWork: 'आपने जो काम किया उसका विवरण दें...', noPortfolio: 'अभी कोई पोर्टफोलियो नहीं',
    noPortfolioSub: 'ज़्यादा ग्राहकों के लिए अपने पुराने काम की फ़ोटो जोड़ें',

    helpTitle: 'सहायता', helpTagline: 'सहायता — हम यहाँ मदद के लिए हैं',
    chatWithUs: 'हमसे चैट करें', whatsappSupport: 'व्हाट्सएप सहायता', fastestResponse: 'सबसे तेज़ जवाब',
    callSupport: 'कॉल सहायता', emailUs: 'हमें ईमेल करें', faqTitle: 'अक्सर पूछे जाने वाले सवाल',
    needMoreHelp: 'और मदद चाहिए?', messageOnWhatsapp: 'व्हाट्सएप पर संदेश भेजें',
    termsConditions: 'नियम व शर्तें', privacyPolicy: 'गोपनीयता नीति',

    walletTitle: 'वॉलेट', walletTaglineWorker: 'मेरी कमाई — आपके कमाई के रिकॉर्ड',
    walletTaglineUser: 'पूरे किए काम के भुगतान रिकॉर्ड',
    filterBy: 'फ़िल्टर करें', monthlyEarnings2: 'महीने की कमाई', monthlyPayments: 'महीने के भुगतान',
    avgEarning: 'औसत कमाई', avgPayment: 'औसत भुगतान', jobsDone2: 'पूरे किए काम',
    completedThisMonth: 'इस महीने पूरे हुए', lifetimeEarnings: 'कुल कमाई',
    lifetimePayments: 'कुल भुगतान', totalRecords: 'कुल रिकॉर्ड',
    earningsHistory: 'कमाई का इतिहास', paymentHistory: 'भुगतान का इतिहास',
    noRecordsIn: (m, y) => `${m} ${y} में कोई रिकॉर्ड नहीं`, tryDifferentMonth: 'दूसरा महीना चुनकर देखें',
    completeFirstJobWorker: 'अपना पहला काम पूरा करें, आपकी कमाई यहाँ दिखेगी',
    completeFirstJobUser: 'किसी मजदूर के साथ काम पूरा करें, रिकॉर्ड यहाँ दिखेगा',
    from: 'से', to2: 'तक', walletInfoWorker: 'आपका काम पूरा होते ही राशि यहाँ अपने आप दिख जाती है। भुगतान सीधे आपके और काम देने वाले के बीच होता है (नकद या UPI) — Instant Worker कोई कमीशन नहीं लेता।',
    walletInfoUser: 'जब आप किसी मजदूर का काम पूरा हुआ मार्क करते हैं, रिकॉर्ड यहाँ अपने आप दिख जाता है। भुगतान सीधे आपके और मजदूर के बीच होता है (नकद या UPI)।',

    idVerificationTitle: 'ID सत्यापन', notVerifiedYet: 'अभी सत्यापित नहीं',
    underReview: 'समीक्षा में', verifiedStatus: 'सत्यापित ✓', verificationRejected: 'सत्यापन अस्वीकृत',
    verifyMyIdentity: 'मेरी पहचान सत्यापित करें', resubmitId: 'फिर से जमा करें',
    idType: 'ID प्रकार', selectIdType: 'ID प्रकार चुनें', idNumberOptional: 'ID नंबर (वैकल्पिक, निजी रखा जाएगा)',
    photoOfId: 'अपने ID की फ़ोटो', tapToUpload: 'फ़ोटो लें या अपलोड करें',
    makeSureVisible: 'सुनिश्चित करें कि सभी जानकारी साफ़ दिख रही है',
    selfieOptional: 'ID के साथ सेल्फ़ी (वैकल्पिक, जल्दी मंज़ूरी में मदद करता है)', tapAddSelfie: 'सेल्फ़ी जोड़ें',
    submitForReview: 'समीक्षा के लिए भेजें', submitting: 'भेजा जा रहा है...',
    privacyNoteVerify: 'आपका ID दस्तावेज़ सिर्फ़ हमारी सत्यापन टीम को दिखता है। हम आपका पूरा ID नंबर कभी सार्वजनिक नहीं करते — सिर्फ़ आखिरी 4 अंक, अगर आप चाहें।',
    getVerifiedBadge: 'अपनी प्रोफाइल पर सत्यापित बैज पाएं। ठेकेदार सत्यापित मजदूरों पर ज़्यादा भरोसा करते हैं।',
    reviewWithin: 'हम 24-48 घंटों में समीक्षा करते हैं।',
    identityVerified: 'आपकी पहचान सत्यापित हो गई है। अब आपकी प्रोफाइल पर सत्यापित बैज दिखेगा।',
    canResubmit: 'आप साफ़ फ़ोटो के साथ फिर से जमा कर सकते हैं।',

    messagesTitle: 'संदेश', messagesTagline: 'बातचीत — आपकी चैट',
    refresh: 'रीफ़्रेश करें', noConversations: 'अभी कोई बातचीत नहीं',
    chatOpensAfter: 'काम स्वीकार होने के बाद चैट खुलती है',
    viewMyJobs: 'मेरे काम देखें', justNow: 'अभी अभी', newBadge: 'नया',
    chatUnlockedSayHello: 'चैट खुल गई — नमस्ते कहें!',
    acceptedFor: (title) => `स्वीकृत: ${title}`,

    notifJobAppliedTitle: 'नया आवेदन!',
    notifJobAppliedBody: (name, job) => `${name} ने आपके काम पर आवेदन किया: ${job}`,
    notifAcceptedTitle: 'आपको काम मिल गया! 🎉',
    notifAcceptedBody: (job) => `"${job}" के लिए आपका आवेदन स्वीकार हो गया। अब आप पोस्टर से चैट कर सकते हैं।`,
    notifRejectedTitle: 'आवेदन नहीं चुना गया',
    notifRejectedBody: (job) => `"${job}" के लिए आपका आवेदन इस बार नहीं चुना गया।`,
    notifWorkStartedTitle: 'काम शुरू हो गया! 🔨',
    notifWorkStartedBody: (name, job) => `${name} ने "${job}" को शुरू हुआ मार्क किया। काम शुरू करने का समय!`,
    notifWorkCompletedTitle: 'काम पूरा हुआ! ✅',
    notifWorkCompletedBody: (name, job, amount) => `${name} ने "${job}" को पूरा हुआ मार्क किया। ₹${amount} आपके वॉलेट रिकॉर्ड में जोड़े गए। रेटिंग देना न भूलें!`,
    notifUrgentJobTitle: '🔴 पास में तुरंत काम!',
    notifUrgentJobBody: (job, skill, city, wage) => `${job} — ${city} में अभी ${skill} चाहिए। ₹${wage}/दिन। जल्दी जवाब दें!`,
    notifUrgentFilledTitle: 'तुरंत वाला काम — मजदूर पुष्टि! ⚡',
    notifUrgentFilledBody: (name, job) => `${name} ने आपका तुरंत वाला काम "${job}" स्वीकार किया और रास्ते में है। चैट अब खुली है।`,

    findWorkTagline: 'काम ढूंढो', searching: 'खोज रहे हैं...',
    jobsAvailable2: (n) => `${n} काम उपलब्ध`,
    skill: 'काम', jobType: 'काम का प्रकार', searchJobsBtn: 'काम खोजें',
    loadingJobs: 'काम लोड हो रहे हैं...', minutesAgo: (n) => `${n} मिनट पहले`, hoursAgo: (n) => `${n} घंटे पहले`, daysAgo: (n) => `${n} दिन पहले`,
    by: 'द्वारा', needed: 'चाहिए', minAgo: 'मिनट पहले',

    loginTagline1: 'हुनरमंद काम,', loginTagline2: 'बस एक टैप दूर।',
    loginValueCopy: 'मिनटों में काम पाएं या सत्यापित मजदूर पाएं — बिना किसी कमीशन, लाइव ट्रैकिंग, और आपकी भाषा में सहायता के साथ।',
    loginBullet1: 'मजदूरों के लिए 100% मुफ़्त — कभी कोई कमीशन नहीं',
    loginBullet2: 'सत्यापित प्रोफाइल और असली रेटिंग',
    loginBullet3: 'लाइव ट्रैकिंग, कैब फॉलो करने जैसी',
    footerCopyright: '© 2026 Instant Worker · आंध्र प्रदेश और तेलंगाना',
    welcomeBackTitle: 'वापसी पर स्वागत है', loginSubtitle: 'अपने खाते में जाने के लिए लॉग इन करें',
    sessionExpiredMsg: 'आपका सेशन समाप्त हो गया। कृपया फिर से लॉग इन करें।',
    mobileNumberField: 'मोबाइल नंबर', tenDigitNumber: '10-अंकों का नंबर',
    passwordField: 'पासवर्ड', yourPasswordPh: 'आपका पासवर्ड',
    loggingInBtn: 'लॉग इन हो रहा है...', logInBtn: 'लॉग इन करें', newHere: 'नए हैं?',
    createFreeAccount: 'मुफ़्त खाता बनाएं',
    byLoggingIn: 'लॉग इन करके आप हमारी', andWord: 'और',
    termsLink: 'नियमों', privacyLink: 'गोपनीयता नीति', agreeSuffix: 'से सहमत होते हैं',
    wrongCredentials: 'गलत फ़ोन नंबर या पासवर्ड',

    createAccountTitle: 'अपना खाता बनाएं', howWillYouUse: 'आप Instant Worker का उपयोग कैसे करेंगे?',
    iWantToWork: 'मुझे काम चाहिए', findJobsNearYou: 'आस-पास के काम ढूंढें',
    iNeedWorkers: 'मुझे मजदूर चाहिए', postJobsAndHire: 'काम पोस्ट करें और मजदूर रखें',
    yourDetailsTitle: 'आपकी जानकारी', weWillVerifyNext: 'अब हम OTP से आपका नंबर सत्यापित करेंगे',
    fullNameLabel: 'पूरा नाम', yourNamePh: 'आपका नाम',
    mobileNumberReg: 'मोबाइल नंबर', tenDigitNumberReg: '10-अंकों का नंबर',
    passwordLabel: 'पासवर्ड', atLeast6Chars: 'कम से कम 6 अक्षर',
    yourMainSkill: 'आपका मुख्य काम', selectSkillPh: 'काम चुनें',
    continueToVerification: 'सत्यापन के लिए आगे बढ़ें', creatingAccount: 'आपका खाता बन रहा है...',
    enterOtpInPopup: 'पॉपअप में अपने फ़ोन पर आया OTP डालें...',
    alreadyHaveAccount: 'पहले से खाता है?', logInLink: 'लॉग इन करें',
    backBtn: 'वापस', registrationUnavailable: 'रजिस्ट्रेशन अभी उपलब्ध नहीं है — OTP सेटअप में समस्या है। कृपया सहायता से संपर्क करें।',
    validPhoneErr: 'सही 10-अंकों का मोबाइल नंबर डालें',
    verifyFailedErr: 'फ़ोन सत्यापन विफल हुआ या रद्द किया गया। कृपया फिर कोशिश करें।',
    couldNotComplete: 'रजिस्ट्रेशन पूरा नहीं हो सका',

    navServices: 'सेवाएं', navHow: 'यह कैसे काम करता है', navAbout: 'हमारे बारे में', navFaq: 'सवाल-जवाब', navContact: 'संपर्क करें',
    loginNav: 'लॉग इन', getStarted: 'शुरू करें',

    heroTagline: 'भारत का इंस्टेंट वर्क प्लेटफॉर्म', heroTaglineCity: (city) => `भारत का इंस्टेंट वर्क प्लेटफॉर्म · ${city}`,
    heroH1a: 'हुनरमंद मजदूर।', heroH1b: 'जब चाहें।', heroH1c: 'मिनटों में।',
    heroSubP1: 'पेंटर, बढ़ई, इलेक्ट्रीशियन, प्लंबर, ड्राइवर और दिहाड़ी मजदूर — सत्यापित मजदूर रखें या अपने पास काम ढूंढें।',
    heroSubP2: 'कोई बिचौलिया नहीं। शून्य कमीशन।',
    heroBtnWork: 'मुझे काम चाहिए', heroBtnHire: 'मुझे मजदूर चाहिए',
    heroStatCommission: 'कमीशन', heroStatRegister: 'रजिस्टर करने में', heroStatLanguages: 'भाषाएं',
    floatWorkerConfirmed: 'मजदूर की पुष्टि हुई', floatArriving: '18 मिनट में पहुंच रहे हैं',
    floatRating: '4.8 रेटिंग', floatVerifiedElectrician: 'ID-सत्यापित इलेक्ट्रीशियन',

    servicesTag: 'हम क्या देते हैं', servicesH2: 'एक प्लेटफॉर्म। दो पक्ष। सब कुछ जो आपको चाहिए।',
    servicesSub: 'चाहे आप रोज़ का काम ढूंढ रहे हों या किसी काम के लिए भरोसेमंद हाथ चाहिए — Instant Worker दोनों पक्षों को सीधे जोड़ता है।',
    forWorkersBadge: 'मजदूरों के लिए', forWorkersTitle: 'अपने पास काम ढूंढें — हमेशा मुफ़्त',
    workerBullet1: 'आपके काम और शहर के हिसाब से काम, सीधे आपके फ़ोन पर',
    workerBullet2: 'अपनी दैनिक मजदूरी खुद तय करें — पूरी कमाई आपकी',
    workerBullet3: 'कभी भी ऑनलाइन/ऑफलाइन जाएं, काम कब करना है यह आप तय करें',
    workerBullet4: 'फ़ोटो पोर्टफोलियो बनाएं और रेटिंग कमाएं जो आपको ज़्यादा काम दिलाए',
    startFindingWork: 'काम ढूंढना शुरू करें',
    forPostersBadge: 'काम देने वालों के लिए', forPostersTitle: 'मिनटों में सत्यापित मजदूर रखें',
    posterBullet1: 'काम पोस्ट करें और पास के कुशल मजदूरों से आवेदन पाएं',
    posterBullet2: 'तुरंत काम — पहला उपलब्ध मजदूर मिनटों में अपने आप पुष्टि हो जाता है',
    posterBullet3: 'अपने मजदूर को मैप पर लाइव आते हुए देखें, कैब की तरह',
    posterBullet4: 'रखने से पहले ID-सत्यापित बैज, रेटिंग, और पुराने काम की फ़ोटो देखें',
    postFirstJob: 'अपना पहला काम पोस्ट करें',

    howTag: 'यह कैसे काम करता है', howH2: 'बस तीन कदम।',
    step1Title: 'मुफ़्त रजिस्टर करें', step1Desc: 'नाम, फ़ोन नंबर, OTP। मजदूर या काम देने वाला चुनें। 2 मिनट से भी कम, कोई दस्तावेज़ नहीं चाहिए।',
    step2Title: 'तुरंत मैच करें', step2Desc: 'मजदूर अपने पास के काम देखते हैं। काम देने वालों को आवेदन मिलते हैं — या तुरंत पुष्टि के लिए Urgent मोड का उपयोग करें।',
    step3Title: 'काम करें और भुगतान पाएं', step3Desc: 'लाइव आगमन ट्रैक करें, काम पूरा करें, सीधे नकद या UPI में भुगतान करें। हम कभी आपके पैसे को नहीं छूते।',

    featUrgentTitle: 'तुरंत काम', featUrgentDesc: 'पहले स्वीकार करने वाले को काम मिलता है — मिनटों में पुष्टि।',
    featTrackTitle: 'लाइव ट्रैकिंग', featTrackDesc: 'अपने मजदूर को मैप पर रीयल टाइम में आते देखें।',
    featIdTitle: 'ID सत्यापन', featIdDesc: 'सरकारी-ID जांचे गए भरोसेमंद बैज।',
    featChatTitle: 'सुरक्षित चैट', featChatDesc: 'पुष्टि के बाद चैट और वॉइस नोट्स खुलते हैं।',
    featZeroTitle: 'शून्य कमीशन', featZeroDesc: 'सीधा भुगतान। मजदूर पूरा पैसा रखते हैं।',
    featLangTitle: '3 भाषाएं', featLangDesc: 'तेलुगु, हिंदी और अंग्रेज़ी — आवाज़ खोज के साथ।',

    aboutTag: 'हमारे बारे में', aboutH2: 'लेबर अड्डे पर खड़े रहने के दिन खत्म हुए।',
    aboutP1: 'हर सुबह, भारत भर में लाखों कुशल मजदूर सड़क के कोनों पर इंतज़ार करते हैं कि कोई उन्हें एक दिन का काम दे। वहीं, जिन्हें ये हुनर चाहिए वे किसी भरोसेमंद को नहीं ढूंढ पाते।',
    aboutP2: (city) => `Instant Worker दोनों पक्षों को सीधे जोड़ता है — कोई एजेंट नहीं, किसी की मजदूरी से कोई कटौती नहीं। ${city} से शुरुआत, तेलुगु, हिंदी और अंग्रेज़ी में बनाया गया ताकि हर कोई इसे इस्तेमाल कर सके, यहां तक कि जो ठीक से पढ़-लिख नहीं सकते।`,
    chipNoMiddlemen: 'कोई बिचौलिया नहीं', chipZeroCommission: 'शून्य कमीशन', chipLocalFirst: 'पहले स्थानीय',
    builtForFairness: 'निष्पक्षता के लिए बनाया गया',

    testimonialsTag: 'प्रशंसापत्र', testimonialsH2: 'लोग क्या कह रहे हैं',
    testi1Name: 'रवि के.', testi1Role: 'पेंटर · हैदराबाद',
    testi1Quote: 'पहले मैं सुबह 6 बजे से लेबर अड्डे पर काम के इंतज़ार में खड़ा रहता था। अब काम मेरे फ़ोन पर आता है। पहले 3 दिनों में ही मुझे 2 पेंटिंग के काम मिले।',
    testi2Name: 'श्रीनिवास टी.', testi2Role: 'काम देने वाले · विजयवाड़ा',
    testi2Quote: 'मुझे तुरंत 2 हेल्पर चाहिए थे। दोनों 20 मिनट के अंदर पुष्टि हो गए और मैं उन्हें मैप पर आते हुए देख सका।',
    testi3Name: 'लक्ष्मी डी.', testi3Role: 'काम देने वाले · विशाखापत्तनम',
    testi3Quote: 'बुक करने से पहले मैंने इलेक्ट्रीशियन की रेटिंग और उनके पुराने काम की फ़ोटो देखी। काम अच्छे से हुआ, बिल्कुल तनाव नहीं।',

    lpFaqTag: 'सवाल-जवाब', lpFaqH2: 'अक्सर पूछे जाने वाले सवाल',
    faq1Q: 'क्या Instant Worker मजदूरों के लिए सच में मुफ़्त है?',
    faq1A: 'हां। रजिस्ट्रेशन मुफ़्त है, काम ढूंढना मुफ़्त है, और हम आपकी मजदूरी से कोई कमीशन नहीं लेते। काम देने वाले के साथ जो भी मजदूरी तय हो, वह 100% आपकी है।',
    faq2Q: 'मजदूरों को भुगतान कैसे मिलता है?',
    faq2A: 'भुगतान सीधे मजदूर और काम देने वाले के बीच होता है — नकद या UPI, जो भी दोनों तय करें। हम सुझाव देते हैं कि काम शुरू करने से पहले चैट में मजदूरी की पुष्टि कर लें, ताकि एक लिखित रिकॉर्ड रहे।',
    faq3Q: 'अगर काम के बाद काम देने वाला भुगतान करने से मना कर दे तो?',
    faq3A: 'तुरंत उनकी प्रोफाइल पर Report बटन से रिपोर्ट करें। हमारी टीम हर रिपोर्ट की जांच करती है। सत्यापित भुगतान शिकायतों वाले उपयोगकर्ताओं को प्लेटफ़ॉर्म से बैन किया जाता है।',
    faq4Q: 'मुझे ठीक से पढ़ना या टाइप करना नहीं आता। क्या मैं फिर भी इसका उपयोग कर सकता हूं?',
    faq4A: 'हां — हमने इसे बिल्कुल आपके जैसे लोगों के लिए बनाया है। आप तेलुगु, हिंदी, या अंग्रेज़ी में बोलकर काम खोज सकते हैं, और काम की जानकारी सुनी जा सकती है। रजिस्ट्रेशन के लिए सिर्फ़ आपका नाम, फ़ोन नंबर, और एक OTP चाहिए।',
    faq5Q: 'ऐप को मेरी लोकेशन क्यों चाहिए?',
    faq5A: 'मजदूर की लाइव लोकेशन सिर्फ़ तभी शेयर होती है जब कोई काम चालू हो, ताकि काम देने वाला देख सके कि वे रास्ते में हैं — कैब ट्रैक करने जैसा। काम पूरा होते ही यह अपने आप बंद हो जाती है।',
    faq6Q: 'अगर मैं सत्यापन करूं तो क्या ID दस्तावेज़ सुरक्षित हैं?',
    faq6A: 'हां। ID सत्यापन वैकल्पिक है। आपका दस्तावेज़ सिर्फ़ हमारी सत्यापन टीम को दिखता है, कभी सार्वजनिक रूप से नहीं दिखाया जाता, और किसी के साथ साझा नहीं किया जाता। आपकी प्रोफाइल पर सिर्फ़ "सत्यापित" बैज दिखता है।',

    contactTag: 'हमसे संपर्क करें', contactH2: 'सवाल हैं? हम मदद के लिए यहां हैं।',
    contactSub: 'सबसे तेज़ जवाब के लिए व्हाट्सएप पर संपर्क करें, या सहायता के समय में कॉल करें। हम हर संदेश का जवाब देते हैं।',
    whatsappLabel: 'व्हाट्सएप', whatsappSub: 'सबसे तेज़ जवाब',
    callUsLabel: 'हमें कॉल करें', emailLabel: 'ईमेल',

    ctaH2: 'आज ही शुरू करें। यह मुफ़्त है।',
    ctaSub: (city) => `मुफ़्त रजिस्ट्रेशन · शून्य कमीशन · ${city}`,
    joinInstantWorker: 'Instant Worker से जुड़ें',

    footerTagline: 'दिहाड़ी मजदूरों को उन लोगों से जोड़ना जिन्हें उनकी ज़रूरत है — तुरंत, निष्पक्ष रूप से, बिना किसी कमीशन के।',
    footerExplore: 'देखें', footerLegalAccount: 'कानूनी और खाता',
    footerRegisterFree: 'मुफ़्त रजिस्टर करें', footerLogin: 'लॉग इन',
    footerTerms: 'नियम व शर्तें', footerPrivacy: 'गोपनीयता नीति',
    footerContact: 'संपर्क करें', footerWhatsappPrefix: 'व्हाट्सएप:',
    footerRights: '© 2026 Instant Worker. सर्वाधिकार सुरक्षित।',
    footerMadeWith: 'के साथ बनाया गया', footerMadeIn: 'आंध्र प्रदेश में',

    marqueePainters: 'पेंटर', marqueeCarpenters: 'बढ़ई', marqueeElectricians: 'इलेक्ट्रीशियन',
    marqueePlumbers: 'प्लंबर', marqueeDrivers: 'ड्राइवर', marqueeWelders: 'वेल्डर',
    marqueeMechanics: 'मैकेनिक', marqueeFarmLabour: 'खेत मजदूर', marqueeHelpers: 'हेल्पर', marqueeMasons: 'राजमिस्त्री',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్', findWork: 'పని వెతకండి', myWork: 'నా పని',
    wallet: 'వాలెట్', history: 'చరిత్ర', messages: 'సందేశాలు',
    portfolio: 'పోర్ట్‌ఫోలియో', notifications: 'నోటిఫికేషన్లు',
    myProfile: 'నా ప్రొఫైల్', verification: 'ధృవీకరణ', help: 'సహాయం',
    logout: 'లాగ్ అవుట్', postJob: 'పని పోస్ట్ చేయండి', myJobPosts: 'నా పనులు',
    findWorkers: 'కార్మికులను వెతకండి', home: 'హోమ్', profile: 'ప్రొఫైల్',
    save: 'సేవ్ చేయండి', cancel: 'రద్దు చేయండి', edit: 'మార్చండి', delete: 'తొలగించండి',
    select: 'ఎంచుకోండి', search: 'వెతకండి', apply: 'దరఖాస్తు చేయండి', loading: 'లోడ్ అవుతోంది...',
    back: 'వెనుకకు', submit: 'సమర్పించండి', close: 'మూసివేయండి', confirm: 'నిర్ధారించండి',
    yourSkill: 'మీ నైపుణ్యం', city: 'నగరం', area: 'ప్రాంతం',
    experience: 'అనుభవం (సంవత్సరాలు)', dailyWage: 'రోజు కూలి (₹)',
    available: 'నేను పనికి అందుబాటులో ఉన్నాను', aboutYou: 'మీ గురించి',
    languages: 'భాషలు', fullName: 'పూర్తి పేరు', phoneNumber: 'మొబైల్ నంబర్',
    age: 'వయస్సు', gender: 'లింగం', saveProfile: 'ప్రొఫైల్ సేవ్ చేయండి',
    editProfile: 'ప్రొఫైల్ మార్చండి', yourRating: 'మీ రేటింగ్',
    browseJobs: 'పనులు చూడండి', noJobs: 'ప్రస్తుతం పనులు అందుబాటులో లేవు',
    jobsAvailable: 'పనులు అందుబాటులో', perDay: 'రోజుకు',
    workersNeeded: 'కార్మికులు కావాలి', applied: 'దరఖాస్తు చేశారు', accepted: 'ఆమోదించబడింది',
    urgent: 'అత్యవసరం', acceptNow: 'ఇప్పుడే అంగీకరించండి', jobPoster: 'పని ఇచ్చేవారు',
    notStarted: 'మొదలవ్వడానికి ఎదురుచూస్తోంది', inProgress: 'పని జరుగుతోంది',
    completed: 'పని పూర్తయింది', markStarted: 'పని మొదలుపెట్టండి',
    markCompleted: 'పని పూర్తి చేయండి', trackWorker: 'కార్మికుడిని ట్రాక్ చేయండి',
    rateWorker: 'కార్మికుడికి రేటింగ్ ఇవ్వండి', rateContractor: 'రేటింగ్ ఇవ్వండి',
    online: 'మీరు ఆన్‌లైన్‌లో ఉన్నారు', offline: 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు',
    goOnline: 'ఆన్‌లైన్ వెళ్ళండి', goOffline: 'ఆఫ్‌లైన్ వెళ్ళండి',
    readyForWork: 'పని అభ్యర్థనలకు సిద్ధంగా ఉన్నారు',
    notReceiving: 'మీకు కొత్త పని నోటిఫికేషన్లు రావు',
    totalEarned: 'మొత్తం సంపాదన', totalPaid: 'మొత్తం చెల్లింపు',
    monthlyEarnings: 'నెలవారీ సంపాదన', averagePerJob: 'ఒక్కో పనికి సగటు',
    jobsDone: 'పూర్తయిన పనులు', noRecords: 'ఇంకా రికార్డులు లేవు',
    goodMorning: 'శుభోదయం', goodAfternoon: 'నమస్కారం',
    goodEvening: 'శుభ సాయంత్రం', quickActions: 'త్వరిత చర్యలు',
    subscription: 'సబ్‌స్క్రిప్షన్',

    jobsPosted: 'పోస్ట్ చేసిన పనులు', rating: 'రేటింగ్', worker: 'కార్మికుడు', user: 'వినియోగదారు',
    readyToReceive: (skill) => `${skill} పని అభ్యర్థనలను స్వీకరించడానికి సిద్ధంగా ఉన్నారు`,
    findWorkTitle: 'పనులు చూడండి',    findWorkSub: 'పని వెతకండి',
    myWorkTitle: 'నా పని',            myWorkSub: 'నా పని చూడండి',
    portfolioTitle: 'పోర్ట్‌ఫోలియో',    portfolioSub: 'పని ఫోటోలు',
    verificationTitle: 'ధృవీకరణ',     verificationSub: 'ID ధృవీకరించండి',
    postJobTitle: 'పని పోస్ట్ చేయండి', postJobSub: 'పని పోస్ట్ చేయండి',
    myJobPostsTitle: 'నా పనులు',       myJobPostsSub: 'నా పోస్ట్‌లు',
    findWorkersTitle: 'కార్మికులను వెతకండి', findWorkersSub: 'వర్కర్ వెతకండి',

    filters: 'ఫిల్టర్లు', clear: 'తొలగించు', clearFilters: 'ఫిల్టర్లు తొలగించండి',
    allSkills: 'అన్ని నైపుణ్యాలు', allCities: 'అన్ని నగరాలు', allTypes: 'అన్ని రకాలు',
    regular: 'సాధారణ', partTime: 'పార్ట్-టైమ్', urgentOnly: 'అత్యవసరం మాత్రమే',
    searchJobs: 'పనులు వెతకండి', voiceSearch: 'వాయిస్ సెర్చ్',
    noJobsFound: 'ప్రస్తుతం పనులు అందుబాటులో లేవు', tryRemovingFilters: 'కొన్ని ఫిల్టర్లు తీసివేయండి, లేదా త్వరలో మళ్ళీ చూడండి',
    willNotify: 'కొత్త పని వచ్చినప్పుడు మేము మీకు తెలియజేస్తాము',
    jobFull: 'స్థానం నిండింది', call: 'కాల్ చేయండి', chat: 'చాట్',
    postedBy: 'పోస్ట్ చేసినవారు', kmAway: 'కి.మీ దూరం',
    showingWithin: (km) => `మీకు ${km}కి.మీ లోపు పనులు చూపిస్తున్నాము`,
    noJobsExpanded: (km) => `6కి.మీ లో పనులు లేవు — ఇప్పుడు ${km}కి.మీ వరకు చూపిస్తున్నాము`,
    locationDenied: 'లొకేషన్ అందుబాటులో లేదు — నగరం/నైపుణ్యం ప్రకారం చూపిస్తున్నాము',

    historyTitle: 'చరిత్ర', historyTagline: 'పాత పనులు — మీ పూర్తయిన పనులు',
    completedJobs: 'పూర్తయిన పనులు', completedOn: 'పూర్తయింది', worked: 'మీరు పని చేశారు',
    rated: 'రేట్ చేయబడింది', ratePoster: 'పోస్టర్‌కి రేటింగ్ ఇవ్వండి', rateWorkerBtn: 'కార్మికుడికి రేటింగ్ ఇవ్వండి',
    noHistory: 'ఇంకా పూర్తయిన పనులు లేవు', noHistoryWorker: 'మీ మొదటి పని పూర్తి చేయండి, ఇది ఇక్కడ కనిపిస్తుంది',
    noHistoryUser: 'కార్మికుడు పని పూర్తి చేసినప్పుడు, ఇది ఇక్కడ కనిపిస్తుంది',

    notifTitle: 'నోటిఫికేషన్లు', notifTagline: 'నోటిఫికేషన్లు — అప్‌డేట్‌గా ఉండండి',
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించండి', clear: 'తొలగించు',
    noNotifs: 'ఇంకా నోటిఫికేషన్లు లేవు', noNotifsSub: 'పని అప్‌డేట్‌లు మరియు సందేశాలు ఇక్కడ కనిపిస్తాయి',

    myPortfolio: 'నా పోర్ట్‌ఫోలియో', portfolioTagline: 'పని ఫోటోలు — మీ ఉత్తమ పనిని చూపించండి',
    addWork: 'పని జోడించండి', addPastWork: 'పాత పని జోడించండి', title: 'శీర్షిక',
    skillUsed: 'ఉపయోగించిన నైపుణ్యం', photosMax: 'ఫోటోలు (గరిష్టం 5)', description: 'వివరణ',
    chooseFiles: 'ఫైల్‌లను ఎంచుకోండి', noFileChosen: 'ఫైల్ ఎంచుకోలేదు',
    describeWork: 'మీరు చేసిన పనిని వివరించండి...', noPortfolio: 'ఇంకా పోర్ట్‌ఫోలియో లేదు',
    noPortfolioSub: 'ఎక్కువ మంది క్లయింట్‌లను ఆకర్షించడానికి మీ పాత పని ఫోటోలను జోడించండి',

    helpTitle: 'సహాయం', helpTagline: 'సహాయం — మేము సహాయం చేయడానికి ఇక్కడ ఉన్నాము',
    chatWithUs: 'మాతో చాట్ చేయండి', whatsappSupport: 'వాట్సాప్ మద్దతు', fastestResponse: 'వేగవంతమైన స్పందన',
    callSupport: 'కాల్ మద్దతు', emailUs: 'మాకు ఇమెయిల్ చేయండి', faqTitle: 'తరచుగా అడిగే ప్రశ్నలు',
    needMoreHelp: 'మరింత సహాయం కావాలా?', messageOnWhatsapp: 'వాట్సాప్‌లో మాకు సందేశం పంపండి',
    termsConditions: 'నిబంధనలు & షరతులు', privacyPolicy: 'గోప్యతా విధానం',

    walletTitle: 'వాలెట్', walletTaglineWorker: 'నా సంపాదన — మీ సంపాదన రికార్డులు',
    walletTaglineUser: 'పూర్తయిన పనుల చెల్లింపు రికార్డులు',
    filterBy: 'ఫిల్టర్ చేయండి', monthlyEarnings2: 'నెలవారీ సంపాదన', monthlyPayments: 'నెలవారీ చెల్లింపులు',
    avgEarning: 'సగటు సంపాదన', avgPayment: 'సగటు చెల్లింపు', jobsDone2: 'పూర్తయిన పనులు',
    completedThisMonth: 'ఈ నెల పూర్తయినవి', lifetimeEarnings: 'మొత్తం సంపాదన',
    lifetimePayments: 'మొత్తం చెల్లింపులు', totalRecords: 'మొత్తం రికార్డులు',
    earningsHistory: 'సంపాదన చరిత్ర', paymentHistory: 'చెల్లింపు చరిత్ర',
    noRecordsIn: (m, y) => `${m} ${y} లో రికార్డులు లేవు`, tryDifferentMonth: 'వేరే నెల ఎంచుకోండి',
    completeFirstJobWorker: 'మీ మొదటి పని పూర్తి చేయండి, మీ సంపాదన ఇక్కడ కనిపిస్తుంది',
    completeFirstJobUser: 'కార్మికుడితో పని పూర్తి చేయండి, రికార్డు ఇక్కడ కనిపిస్తుంది',
    from: 'నుండి', to2: 'వరకు', walletInfoWorker: 'మీ పని పూర్తయినప్పుడు మొత్తం ఇక్కడ స్వయంచాలకంగా కనిపిస్తుంది. చెల్లింపు నేరుగా మీకు మరియు పని ఇచ్చినవారికి మధ్య జరుగుతుంది (నగదు లేదా UPI) — Instant Worker ఎలాంటి కమీషన్ తీసుకోదు.',
    walletInfoUser: 'మీరు కార్మికుడి పని పూర్తయినట్లు గుర్తించినప్పుడు, రికార్డు ఇక్కడ స్వయంచాలకంగా కనిపిస్తుంది. చెల్లింపు నేరుగా మీకు మరియు కార్మికుడికి మధ్య జరుగుతుంది (నగదు లేదా UPI).',

    idVerificationTitle: 'ID ధృవీకరణ', notVerifiedYet: 'ఇంకా ధృవీకరించబడలేదు',
    underReview: 'సమీక్షలో ఉంది', verifiedStatus: 'ధృవీకరించబడింది ✓', verificationRejected: 'ధృవీకరణ తిరస్కరించబడింది',
    verifyMyIdentity: 'నా గుర్తింపును ధృవీకరించండి', resubmitId: 'మళ్ళీ సమర్పించండి',
    idType: 'ID రకం', selectIdType: 'ID రకాన్ని ఎంచుకోండి', idNumberOptional: 'ID నంబర్ (ఐచ్ఛికం, ప్రైవేట్‌గా ఉంచబడుతుంది)',
    photoOfId: 'మీ ID ఫోటో', tapToUpload: 'ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి',
    makeSureVisible: 'అన్ని వివరాలు స్పష్టంగా కనిపించేలా చూసుకోండి',
    selfieOptional: 'ID తో సెల్ఫీ (ఐచ్ఛికం, వేగవంతమైన ఆమోదానికి సహాయపడుతుంది)', tapAddSelfie: 'సెల్ఫీ జోడించండి',
    submitForReview: 'సమీక్ష కోసం సమర్పించండి', submitting: 'సమర్పిస్తోంది...',
    privacyNoteVerify: 'మీ ID పత్రం మా ధృవీకరణ బృందానికి మాత్రమే కనిపిస్తుంది. మేము మీ పూర్తి ID నంబర్‌ను బహిరంగంగా ఎప్పుడూ చూపించము — మీరు పంచుకోవాలనుకుంటే చివరి 4 అంకెలు మాత్రమే.',
    getVerifiedBadge: 'మీ ప్రొఫైల్‌పై ధృవీకరించబడిన బ్యాడ్జ్ పొందండి. కాంట్రాక్టర్లు ధృవీకరించిన కార్మికులను ఎక్కువగా నమ్ముతారు.',
    reviewWithin: 'మేము 24-48 గంటలలో సమీక్షిస్తాము.',
    identityVerified: 'మీ గుర్తింపు ధృవీకరించబడింది. ఇప్పుడు మీ ప్రొఫైల్‌పై ధృవీకరించిన బ్యాడ్జ్ కనిపిస్తుంది.',
    canResubmit: 'మీరు స్పష్టమైన ఫోటోతో మళ్ళీ సమర్పించవచ్చు.',

    messagesTitle: 'సందేశాలు', messagesTagline: 'సంభాషణ — మీ చాట్‌లు',
    refresh: 'రిఫ్రెష్ చేయండి', noConversations: 'ఇంకా సంభాషణలు లేవు',
    chatOpensAfter: 'పని దరఖాస్తు ఆమోదించిన తర్వాత చాట్ తెరుచుకుంటుంది',
    viewMyJobs: 'నా పనులు చూడండి', justNow: 'ఇప్పుడే', newBadge: 'కొత్తది',
    chatUnlockedSayHello: 'చాట్ తెరిచింది — హలో చెప్పండి!',
    acceptedFor: (title) => `ఆమోదించబడింది: ${title}`,

    notifJobAppliedTitle: 'కొత్త దరఖాస్తు!',
    notifJobAppliedBody: (name, job) => `${name} మీ పని కోసం దరఖాస్తు చేశారు: ${job}`,
    notifAcceptedTitle: 'మీకు పని దొరికింది! 🎉',
    notifAcceptedBody: (job) => `"${job}" కోసం మీ దరఖాస్తు ఆమోదించబడింది. ఇప్పుడు మీరు పోస్టర్‌తో చాట్ చేయవచ్చు.`,
    notifRejectedTitle: 'దరఖాస్తు ఎంపిక కాలేదు',
    notifRejectedBody: (job) => `"${job}" కోసం మీ దరఖాస్తు ఈసారి ఎంపిక కాలేదు.`,
    notifWorkStartedTitle: 'పని ప్రారంభమైంది! 🔨',
    notifWorkStartedBody: (name, job) => `${name} "${job}" ను ప్రారంభమైనట్లు గుర్తించారు. పని మొదలుపెట్టే సమయం!`,
    notifWorkCompletedTitle: 'పని పూర్తయింది! ✅',
    notifWorkCompletedBody: (name, job, amount) => `${name} "${job}" ను పూర్తయినట్లు గుర్తించారు. ₹${amount} మీ వాలెట్ రికార్డులకు జోడించబడింది. రేటింగ్ ఇవ్వడం మర్చిపోవద్దు!`,
    notifUrgentJobTitle: '🔴 సమీపంలో అత్యవసర పని!',
    notifUrgentJobBody: (job, skill, city, wage) => `${job} — ${city} లో ఇప్పుడే ${skill} కావాలి. ₹${wage}/రోజు. త్వరగా స్పందించండి!`,
    notifUrgentFilledTitle: 'అత్యవసర పని — కార్మికుడు నిర్ధారించారు! ⚡',
    notifUrgentFilledBody: (name, job) => `${name} మీ అత్యవసర పని "${job}" ను అంగీకరించారు మరియు వస్తున్నారు. చాట్ ఇప్పుడు తెరిచి ఉంది.`,

    findWorkTagline: 'పని వెతకండి', searching: 'వెతుకుతోంది...',
    jobsAvailable2: (n) => `${n} పనులు అందుబాటులో`,
    skill: 'నైపుణ్యం', jobType: 'పని రకం', searchJobsBtn: 'పనులు వెతకండి',
    loadingJobs: 'పనులు లోడ్ అవుతున్నాయి...', minutesAgo: (n) => `${n} నిమిషాల క్రితం`, hoursAgo: (n) => `${n} గంటల క్రితం`, daysAgo: (n) => `${n} రోజుల క్రితం`,
    by: 'ద్వారా', needed: 'కావాలి', minAgo: 'నిమిషాల క్రితం',

    loginTagline1: 'నైపుణ్యం గల పని,', loginTagline2: 'ఒక్క టాప్ దూరంలో.',
    loginValueCopy: 'నిమిషాల్లో పని పొందండి లేదా ధృవీకరించిన కార్మికులను నియమించుకోండి — ఎలాంటి కమీషన్ లేకుండా, లైవ్ ట్రాకింగ్‌తో, మీ భాషలో మద్దతుతో.',
    loginBullet1: 'కార్మికులకు 100% ఉచితం — ఎప్పుడూ కమీషన్ లేదు',
    loginBullet2: 'ధృవీకరించిన ప్రొఫైల్‌లు, నిజమైన రేటింగ్‌లు',
    loginBullet3: 'లైవ్ ట్రాకింగ్, క్యాబ్‌ను ఫాలో అయినట్లు',
    footerCopyright: '© 2026 Instant Worker · ఆంధ్రప్రదేశ్ & తెలంగాణ',
    welcomeBackTitle: 'తిరిగి స్వాగతం', loginSubtitle: 'మీ ఖాతాలోకి కొనసాగించడానికి లాగిన్ అవ్వండి',
    sessionExpiredMsg: 'మీ సెషన్ ముగిసింది. దయచేసి మళ్ళీ లాగిన్ అవ్వండి.',
    mobileNumberField: 'మొబైల్ నంబర్', tenDigitNumber: '10-అంకెల నంబర్',
    passwordField: 'పాస్‌వర్డ్', yourPasswordPh: 'మీ పాస్‌వర్డ్',
    loggingInBtn: 'లాగిన్ అవుతోంది...', logInBtn: 'లాగిన్ అవ్వండి', newHere: 'కొత్తగా వచ్చారా?',
    createFreeAccount: 'ఉచిత ఖాతా సృష్టించండి',
    byLoggingIn: 'లాగిన్ అవ్వడం ద్వారా మీరు మా', andWord: 'మరియు',
    termsLink: 'నిబంధనలు', privacyLink: 'గోప్యతా విధానం', agreeSuffix: 'కి అంగీకరిస్తున్నారు',
    wrongCredentials: 'తప్పు ఫోన్ నంబర్ లేదా పాస్‌వర్డ్',

    createAccountTitle: 'మీ ఖాతా సృష్టించండి', howWillYouUse: 'మీరు Instant Workerని ఎలా ఉపయోగిస్తారు?',
    iWantToWork: 'నాకు పని కావాలి', findJobsNearYou: 'సమీపంలోని పనులు వెతకండి',
    iNeedWorkers: 'నాకు కార్మికులు కావాలి', postJobsAndHire: 'పని పోస్ట్ చేసి నియమించుకోండి',
    yourDetailsTitle: 'మీ వివరాలు', weWillVerifyNext: 'ఇప్పుడు మేము OTP తో మీ నంబర్‌ను ధృవీకరిస్తాము',
    fullNameLabel: 'పూర్తి పేరు', yourNamePh: 'మీ పేరు',
    mobileNumberReg: 'మొబైల్ నంబర్', tenDigitNumberReg: '10-అంకెల నంబర్',
    passwordLabel: 'పాస్‌వర్డ్', atLeast6Chars: 'కనీసం 6 అక్షరాలు',
    yourMainSkill: 'మీ ప్రధాన నైపుణ్యం', selectSkillPh: 'నైపుణ్యం ఎంచుకోండి',
    continueToVerification: 'ధృవీకరణకు కొనసాగండి', creatingAccount: 'మీ ఖాతా సృష్టించబడుతోంది...',
    enterOtpInPopup: 'పాప్అప్‌లో మీ ఫోన్‌కు వచ్చిన OTP నమోదు చేయండి...',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?', logInLink: 'లాగిన్ అవ్వండి',
    backBtn: 'వెనుకకు', registrationUnavailable: 'నమోదు ప్రస్తుతం అందుబాటులో లేదు — OTP సెటప్‌లో సమస్య ఉంది. దయచేసి సహాయాన్ని సంప్రదించండి.',
    validPhoneErr: 'సరైన 10-అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
    verifyFailedErr: 'ఫోన్ ధృవీకరణ విఫలమైంది లేదా రద్దు చేయబడింది. దయచేసి మళ్ళీ ప్రయత్నించండి.',
    couldNotComplete: 'నమోదు పూర్తి కాలేదు',

    navServices: 'సేవలు', navHow: 'ఇది ఎలా పనిచేస్తుంది', navAbout: 'మా గురించి', navFaq: 'ప్రశ్నలు', navContact: 'సంప్రదించండి',
    loginNav: 'లాగిన్', getStarted: 'ప్రారంభించండి',

    heroTagline: 'భారతదేశ తక్షణ పని వేదిక', heroTaglineCity: (city) => `భారతదేశ తక్షణ పని వేదిక · ${city}`,
    heroH1a: 'నైపుణ్యం గల కార్మికులు.', heroH1b: 'డిమాండ్ మేరకు.', heroH1c: 'నిమిషాల్లో.',
    heroSubP1: 'పెయింటర్లు, వడ్రంగులు, ఎలక్ట్రీషియన్లు, ప్లంబర్లు, డ్రైవర్లు మరియు రోజువారీ కూలీలు — ధృవీకరించిన కార్మికులను నియమించుకోండి లేదా మీ దగ్గర పని వెతకండి.',
    heroSubP2: 'మధ్యవర్తులు లేరు. కమీషన్ లేదు.',
    heroBtnWork: 'నాకు పని కావాలి', heroBtnHire: 'నాకు కార్మికులు కావాలి',
    heroStatCommission: 'కమీషన్', heroStatRegister: 'నమోదు చేసుకోవడానికి', heroStatLanguages: 'భాషలు',
    floatWorkerConfirmed: 'కార్మికుడు నిర్ధారించబడ్డారు', floatArriving: '18 నిమిషాల్లో చేరుకుంటున్నారు',
    floatRating: '4.8 రేటింగ్', floatVerifiedElectrician: 'ID-ధృవీకరించిన ఎలక్ట్రీషియన్',

    servicesTag: 'మేము అందించేవి', servicesH2: 'ఒక వేదిక. రెండు వైపులు. మీకు కావలసినవన్నీ.',
    servicesSub: 'మీరు రోజువారీ పని వెతుకుతున్నా లేదా ఒక పని కోసం నమ్మకమైన సహాయం కావాలన్నా — Instant Worker రెండు వైపులను నేరుగా కలుపుతుంది.',
    forWorkersBadge: 'కార్మికుల కోసం', forWorkersTitle: 'మీ దగ్గర పని వెతకండి — ఎప్పటికీ ఉచితం',
    workerBullet1: 'మీ నైపుణ్యం మరియు నగరానికి సరిపోలే పనులు, నేరుగా మీ ఫోన్‌కు',
    workerBullet2: 'మీ సొంత రోజు కూలి మీరే నిర్ణయించండి — 100% మీదే',
    workerBullet3: 'ఎప్పుడైనా ఆన్‌లైన్ / ఆఫ్‌లైన్ వెళ్ళండి, ఎప్పుడు పని చేయాలో మీరే నిర్ణయిస్తారు',
    workerBullet4: 'ఫోటో పోర్ట్‌ఫోలియో నిర్మించండి మరియు ఎక్కువ పని దొరికేలా రేటింగ్‌లు సంపాదించండి',
    startFindingWork: 'పని వెతకడం మొదలుపెట్టండి',
    forPostersBadge: 'పని ఇచ్చేవారి కోసం', forPostersTitle: 'నిమిషాల్లో ధృవీకరించిన కార్మికులను నియమించుకోండి',
    posterBullet1: 'పని పోస్ట్ చేసి సమీపంలోని నైపుణ్యం గల కార్మికుల నుండి దరఖాస్తులు పొందండి',
    posterBullet2: 'అత్యవసర నియామకం — మొదట అందుబాటులో ఉన్న కార్మికుడు నిమిషాల్లో స్వయంచాలకంగా నిర్ధారించబడతారు',
    posterBullet3: 'మీ కార్మికుడు మ్యాప్‌లో లైవ్‌గా వస్తుండగా చూడండి, క్యాబ్ లాగా',
    posterBullet4: 'నియమించుకునే ముందు ID-ధృవీకరించిన బ్యాడ్జ్‌లు, రేటింగ్‌లు, మరియు పాత పని ఫోటోలను తనిఖీ చేయండి',
    postFirstJob: 'మీ మొదటి పని పోస్ట్ చేయండి',

    howTag: 'ఇది ఎలా పనిచేస్తుంది', howH2: 'మూడు దశలు. అంతే.',
    step1Title: 'ఉచితంగా నమోదు చేసుకోండి', step1Desc: 'పేరు, ఫోన్ నంబర్, OTP. కార్మికుడు లేదా పని ఇచ్చేవారు ఎంచుకోండి. 2 నిమిషాల్లోపు, పత్రాలు అవసరం లేదు.',
    step2Title: 'తక్షణమే మ్యాచ్ చేయండి', step2Desc: 'కార్మికులు తమ దగ్గర పనులను చూస్తారు. పోస్టర్లకు దరఖాస్తులు వస్తాయి — లేదా తక్షణ నిర్ధారణ కోసం Urgent మోడ్ ఉపయోగించండి.',
    step3Title: 'పని చేసి చెల్లింపు పొందండి', step3Desc: 'రాకను లైవ్‌గా ట్రాక్ చేయండి, పని పూర్తి చేయండి, నేరుగా నగదు లేదా UPI లో చెల్లించండి. మేము మీ డబ్బును ఎప్పుడూ ముట్టుకోము.',

    featUrgentTitle: 'అత్యవసర నియామకం', featUrgentDesc: 'మొదట అంగీకరించినవారికి పని — నిమిషాల్లో నిర్ధారణ.',
    featTrackTitle: 'లైవ్ ట్రాకింగ్', featTrackDesc: 'మీ కార్మికుడు మ్యాప్‌లో రియల్ టైమ్‌లో రావడం చూడండి.',
    featIdTitle: 'ID ధృవీకరణ', featIdDesc: 'ప్రభుత్వ-ID తనిఖీ చేసిన నమ్మదగిన బ్యాడ్జ్‌లు.',
    featChatTitle: 'సురక్షిత చాట్', featChatDesc: 'నిర్ధారణ తర్వాత చాట్ మరియు వాయిస్ నోట్స్ తెరుచుకుంటాయి.',
    featZeroTitle: 'కమీషన్ లేదు', featZeroDesc: 'నేరుగా చెల్లింపు. కార్మికులు ప్రతి రూపాయిని ఉంచుకుంటారు.',
    featLangTitle: '3 భాషలు', featLangDesc: 'తెలుగు, హిందీ మరియు ఇంగ్లీష్ — వాయిస్ సెర్చ్‌తో.',

    aboutTag: 'మా గురించి', aboutH2: 'లేబర్ అడ్డా వద్ద నిలబడే రోజులు ముగిశాయి.',
    aboutP1: 'ప్రతి ఉదయం, భారతదేశవ్యాప్తంగా లక్షలాది నైపుణ్యం గల కార్మికులు ఎవరైనా ఒక రోజు పని ఇస్తారని ఆశతో వీధి మలుపుల్లో వేచి ఉంటారు. అదే సమయంలో, ఆ నైపుణ్యాలు కావలసిన వారికి నమ్మదగిన వారు దొరకరు.',
    aboutP2: (city) => `Instant Worker రెండు వైపులను నేరుగా కలుపుతుంది — ఏజెంట్లు లేరు, ఎవరి కూలి నుండి కోతలు లేవు. ${city} లో ప్రారంభమై, తెలుగు, హిందీ మరియు ఇంగ్లీష్‌లో నిర్మించబడింది కాబట్టి సరిగ్గా చదవడం లేదా టైప్ చేయడం రాని వారితో సహా అందరూ దీన్ని ఉపయోగించవచ్చు.`,
    chipNoMiddlemen: 'మధ్యవర్తులు లేరు', chipZeroCommission: 'కమీషన్ లేదు', chipLocalFirst: 'స్థానికత మొదట',
    builtForFairness: 'న్యాయం కోసం నిర్మించబడింది',

    testimonialsTag: 'ప్రశంసలు', testimonialsH2: 'ప్రజలు ఏమి చెబుతున్నారు',
    testi1Name: 'రవి కె.', testi1Role: 'పెయింటర్ · హైదరాబాద్',
    testi1Quote: 'ముందు నేను ఉదయం 6 గంటల నుండి లేబర్ అడ్డా వద్ద పని కోసం ఎదురుచూస్తూ నిలబడేవాడిని. ఇప్పుడు పని నా ఫోన్‌కు వస్తుంది. మొదటి 3 రోజుల్లోనే నాకు 2 పెయింటింగ్ పనులు దొరికాయి.',
    testi2Name: 'శ్రీనివాస్ టి.', testi2Role: 'పని ఇచ్చినవారు · విజయవాడ',
    testi2Quote: 'నాకు అత్యవసరంగా 2 హెల్పర్లు కావాలి. ఇద్దరూ 20 నిమిషాల్లో నిర్ధారించబడ్డారు మరియు వారు మ్యాప్‌లో రావడం నేను చూడగలిగాను.',
    testi3Name: 'లక్ష్మి డి.', testi3Role: 'పని ఇచ్చినవారు · విశాఖపట్నం',
    testi3Quote: 'బుక్ చేయడానికి ముందు నేను ఎలక్ట్రీషియన్ రేటింగ్ మరియు అతని పాత పని ఫోటోలను తనిఖీ చేశాను. పని బాగా జరిగింది, ఎలాంటి ఒత్తిడి లేదు.',

    lpFaqTag: 'ప్రశ్నలు', lpFaqH2: 'తరచుగా అడిగే ప్రశ్నలు',
    faq1Q: 'Instant Worker నిజంగా కార్మికులకు ఉచితమా?',
    faq1A: 'అవును. నమోదు ఉచితం, పనులు వెతకడం ఉచితం, మరియు మేము మీ వేతనం నుండి ఎలాంటి కమీషన్ తీసుకోము. పని ఇచ్చినవారితో మీరు అంగీకరించిన వేతనం 100% మీదే.',
    faq2Q: 'కార్మికులకు చెల్లింపు ఎలా జరుగుతుంది?',
    faq2A: 'చెల్లింపు నేరుగా కార్మికుడు మరియు పని ఇచ్చినవారి మధ్య జరుగుతుంది — నగదు లేదా UPI, ఇద్దరూ అంగీకరించినది ఏదైనా. పని మొదలుపెట్టే ముందు చాట్‌లో వేతనాన్ని నిర్ధారించుకోవాలని మేము సూచిస్తున్నాము, తద్వారా వ్రాతపూర్వక రికార్డు ఉంటుంది.',
    faq3Q: 'పని తర్వాత పోస్టర్ చెల్లించడానికి నిరాకరిస్తే?',
    faq3A: 'వెంటనే వారి ప్రొఫైల్‌లో Report బటన్‌తో రిపోర్ట్ చేయండి. మా బృందం ప్రతి రిపోర్ట్‌ను సమీక్షిస్తుంది. ధృవీకరించిన చెల్లింపు ఫిర్యాదులు ఉన్న వినియోగదారులు ప్లాట్‌ఫారమ్ నుండి నిషేధించబడతారు.',
    faq4Q: 'నాకు సరిగ్గా చదవడం లేదా టైప్ చేయడం రాదు. నేను దీన్ని ఉపయోగించవచ్చా?',
    faq4A: 'అవును — మేము దీన్ని మీలాంటి వారి కోసమే తయారు చేసాము. మీరు తెలుగు, హిందీ, లేదా ఇంగ్లీష్‌లో మాట్లాడి పనులను వెతకవచ్చు, మరియు పని వివరాలు వినిపించవచ్చు. నమోదుకు కేవలం మీ పేరు, ఫోన్ నంబర్, మరియు OTP మాత్రమే కావాలి.',
    faq5Q: 'యాప్‌కు నా లొకేషన్ ఎందుకు కావాలి?',
    faq5A: 'పని జరుగుతున్నప్పుడు మాత్రమే కార్మికుడి లైవ్ లొకేషన్ షేర్ చేయబడుతుంది, తద్వారా పని ఇచ్చినవారు వారు వస్తున్నారని చూడగలరు — క్యాబ్‌ను ట్రాక్ చేసినట్లు. పని పూర్తయినప్పుడు ఇది స్వయంచాలకంగా ఆగిపోతుంది.',
    faq6Q: 'నేను ధృవీకరిస్తే ID పత్రాలు సురక్షితమేనా?',
    faq6A: 'అవును. ID ధృవీకరణ ఐచ్ఛికం. మీ పత్రం మా ధృవీకరణ బృందానికి మాత్రమే కనిపిస్తుంది, ఎప్పుడూ బహిరంగంగా చూపబడదు, మరియు ఎవరితోనూ పంచుకోబడదు. మీ ప్రొఫైల్‌పై "ధృవీకరించబడింది" బ్యాడ్జ్ మాత్రమే కనిపిస్తుంది.',

    contactTag: 'మమ్మల్ని సంప్రదించండి', contactH2: 'ప్రశ్నలు ఉన్నాయా? మేము సహాయం చేయడానికి ఇక్కడ ఉన్నాము.',
    contactSub: 'వేగవంతమైన స్పందన కోసం వాట్సాప్‌లో సంప్రదించండి, లేదా మద్దతు సమయంలో కాల్ చేయండి. మేము ప్రతి సందేశానికి స్పందిస్తాము.',
    whatsappLabel: 'వాట్సాప్', whatsappSub: 'వేగవంతమైన స్పందన',
    callUsLabel: 'మాకు కాల్ చేయండి', emailLabel: 'ఇమెయిల్',

    ctaH2: 'ఈరోజే ప్రారంభించండి. ఇది ఉచితం.',
    ctaSub: (city) => `ఉచిత నమోదు · కమీషన్ లేదు · ${city}`,
    joinInstantWorker: 'Instant Workerలో చేరండి',

    footerTagline: 'రోజువారీ కూలీలను వారు కావలసిన వారితో కలుపుతోంది — తక్షణమే, న్యాయంగా, ఎలాంటి కమీషన్ లేకుండా.',
    footerExplore: 'అన్వేషించండి', footerLegalAccount: 'చట్టపరమైన & ఖాతా',
    footerRegisterFree: 'ఉచితంగా నమోదు చేసుకోండి', footerLogin: 'లాగిన్',
    footerTerms: 'నిబంధనలు & షరతులు', footerPrivacy: 'గోప్యతా విధానం',
    footerContact: 'సంప్రదించండి', footerWhatsappPrefix: 'వాట్సాప్:',
    footerRights: '© 2026 Instant Worker. అన్ని హక్కులు రక్షించబడ్డాయి.',
    footerMadeWith: 'తో తయారు చేయబడింది', footerMadeIn: 'ఆంధ్రప్రదేశ్‌లో',

    marqueePainters: 'పెయింటర్లు', marqueeCarpenters: 'వడ్రంగులు', marqueeElectricians: 'ఎలక్ట్రీషియన్లు',
    marqueePlumbers: 'ప్లంబర్లు', marqueeDrivers: 'డ్రైవర్లు', marqueeWelders: 'వెల్డర్లు',
    marqueeMechanics: 'మెకానిక్‌లు', marqueeFarmLabour: 'వ్యవసాయ కూలీలు', marqueeHelpers: 'హెల్పర్లు', marqueeMasons: 'తాపీ మేస్త్రీలు',
  },
};

export function LangProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    try {
      const saved = localStorage.getItem('lang');
      return ['en', 'hi', 'te'].includes(saved) ? saved : 'en';
    } catch { return 'en'; }
  });

  const setLang = (code) => {
    if (!['en', 'hi', 'te'].includes(code)) return;
    setLangState(code);
    try { localStorage.setItem('lang', code); } catch {}
  };

  useEffect(() => { document.documentElement.lang = lang; }, [lang]);

  // t(key) for plain strings, t(key, arg) for single-argument functions
  // (e.g. t('showingWithin', 15)), t(key, [a, b, c]) for multi-argument
  // functions (e.g. t('notifWorkCompletedBody', [name, job, amount])).
  const t = (key, arg) => {
    const val = STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
    if (typeof val !== 'function') return val;
    return Array.isArray(arg) ? val(...arg) : val(arg);
  };

  return (
    <LangContext.Provider value={{
      lang, setLang, t,
      changeLang: setLang,
      languages: LANGUAGES,
    }}>
      {children}
    </LangContext.Provider>
  );
}

export default LangContext;